name: Deploy

# 手动触发工作流
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'  # 根据项目需要选择 Java 版本

      - name: Build with Maven
        run: mvn clean package

      - name: List target directories
        run: |
          ls -l
          ls -l emeifeng-serve-web-starter/target
          ls -l emeifeng-serve-web-service/target
          ls -l emeifeng-serve-web-infrastructure/target

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          HOST: 81.70.198.221
          USER: ubuntu
          TEMP_PATH: /home/ubuntu/temp
          DEPLOY_PATH: /var/www/emeifeng-serve
          SERVICE_NAME: emeifeng-serve
        run: |
          echo "Creating temporary directory on server..."
          ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p $TEMP_PATH"

          echo "Finding JAR files..."
          JAR_FILES=(
            "emeifeng-serve-web-starter/target/*.jar"
            "emeifeng-serve-web-service/target/*.jar"
            "emeifeng-serve-web-infrastructure/target/*.jar"
          )

          for JAR_FILE_PATTERN in "${JAR_FILES[@]}"; do
            JAR_FILE=$(echo $JAR_FILE_PATTERN)
            if [ ! -f $JAR_FILE ]; then
              echo "Error: JAR file matching pattern $JAR_FILE_PATTERN not found"
              exit 1
            fi

            echo "Transferring JAR file $JAR_FILE..."
            scp -o StrictHostKeyChecking=no $JAR_FILE $USER@$HOST:$TEMP_PATH || { echo "SCP failed for $JAR_FILE"; exit 1; }
          done

          echo "Deploying on server..."
          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            sudo systemctl stop $SERVICE_NAME || { echo "Failed to stop service"; exit 1; }
            sudo rm -rf $DEPLOY_PATH/*.jar || { echo "Failed to remove old JARs"; exit 1; }
            sudo mv $TEMP_PATH/*.jar $DEPLOY_PATH/ || { echo "Failed to move new JARs"; exit 1; }
            sudo systemctl start $SERVICE_NAME || { echo "Failed to start service"; exit 1; }
            rm -rf $TEMP_PATH
          EOF
