name: Deploy

# 手动触发工作流
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'  # 根据项目需要选择 Java 版本

      - name: Build with Maven
        run: mvn clean package spring-boot:repackage

      - name: List target directory
        run: ls -l target

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          HOST: 81.70.198.221
          USER: ubuntu
          TEMP_PATH: /home/ubuntu/temp
          DEPLOY_PATH: /var/www/emeifeng-serve
          SERVICE_NAME: emeifeng-serve
        run: |
          echo "Creating temporary directory on server..."
          ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p $TEMP_PATH"

          echo "Finding JAR files..."
          JAR_FILES=$(find target -name "*.jar" -not -path "*/target/original-*.jar")

          if [ -z "$JAR_FILES" ]; then
            echo "Error: No JAR files found"
            exit 1
          fi

          echo "Transferring JAR files..."
          for jar in $JAR_FILES; do
            scp -o StrictHostKeyChecking=no $jar $USER@$HOST:$TEMP_PATH || { echo "SCP failed"; exit 1; }
          done

          echo "Deploying on server..."
          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            sudo systemctl stop $SERVICE_NAME || { echo "Failed to stop service"; exit 1; }
            sudo rm -rf $DEPLOY_PATH/*.jar || { echo "Failed to remove old JARs"; exit 1; }
            sudo mv $TEMP_PATH/*.jar $DEPLOY_PATH/ || { echo "Failed to move new JARs"; exit 1; }
            sudo systemctl start $SERVICE_NAME || { echo "Failed to start service"; exit 1; }
            rm -rf $TEMP_PATH
          EOF
