name: Deploy

# 手动触发工作流
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'  # 根据项目需要选择 Java 版本

      - name: Build with Maven
        run: mvn clean package spring-boot:repackage

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          HOST: 81.70.198.221
          USER: ubuntu
          TEMP_PATH: /home/ubuntu/temp
          DEPLOY_PATH: /var/www/emeifeng-serve
          SERVICE_NAME: emeifeng-serve
        run: |
          # 确保临时目录存在
          ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p $TEMP_PATH"

          # 获取所有生成的 JAR 文件
          JAR_FILES=$(find target -name "*.jar" -not -path "*/target/original-*.jar")

          # 检查 JAR 文件是否存在
          if [ -z "$JAR_FILES" ]; then
            echo "Error: No JAR files found"
            exit 1
          fi

          # 将构建的 JAR 文件传输到临时目录
          for jar in $JAR_FILES; do
            scp -o StrictHostKeyChecking=no $jar $USER@$HOST:$TEMP_PATH
          done

          # 连接到服务器并执行部署脚本
          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            # 停止当前服务
            sudo systemctl stop $SERVICE_NAME
          
            # 删除旧服务文件
            sudo rm -rf $DEPLOY_PATH/*.jar

            # 移动 JAR 文件到目标目录
            sudo mv $TEMP_PATH/*.jar $DEPLOY_PATH/

            # 启动服务
            sudo systemctl start $SERVICE_NAME

            # 清理临时目录
            rm -rf $TEMP_PATH
          EOF
